// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file BBoxesData.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "BBoxesData.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

#define BBoxesData_max_cdr_typesize 31208ULL;
#define BBoxData_max_cdr_typesize 312ULL;
#define BBoxesData_max_key_cdr_typesize 0ULL;
#define BBoxData_max_key_cdr_typesize 0ULL;

BBoxesData::BBoxesData()
{
    // short m_system_ID
    m_system_ID = 0;
    // sequence<BBoxData> m_bounding_boxes


}

BBoxesData::~BBoxesData()
{


}

BBoxesData::BBoxesData(
        const BBoxesData& x)
{
    m_system_ID = x.m_system_ID;
    m_bounding_boxes = x.m_bounding_boxes;
}

BBoxesData::BBoxesData(
        BBoxesData&& x) noexcept 
{
    m_system_ID = x.m_system_ID;
    m_bounding_boxes = std::move(x.m_bounding_boxes);
}

BBoxesData& BBoxesData::operator =(
        const BBoxesData& x)
{

    m_system_ID = x.m_system_ID;
    m_bounding_boxes = x.m_bounding_boxes;

    return *this;
}

BBoxesData& BBoxesData::operator =(
        BBoxesData&& x) noexcept
{

    m_system_ID = x.m_system_ID;
    m_bounding_boxes = std::move(x.m_bounding_boxes);

    return *this;
}

bool BBoxesData::operator ==(
        const BBoxesData& x) const
{

    return (m_system_ID == x.m_system_ID && m_bounding_boxes == x.m_bounding_boxes);
}

bool BBoxesData::operator !=(
        const BBoxesData& x) const
{
    return !(*this == x);
}

size_t BBoxesData::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return BBoxesData_max_cdr_typesize;
}

size_t BBoxesData::getCdrSerializedSize(
        const BBoxesData& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 2 + eprosima::fastcdr::Cdr::alignment(current_alignment, 2);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    for(size_t a = 0; a < data.bounding_boxes().size(); ++a)
    {
        current_alignment += BBoxData::getCdrSerializedSize(data.bounding_boxes().at(a), current_alignment);}


    return current_alignment - initial_alignment;
}

void BBoxesData::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_system_ID;
    scdr << m_bounding_boxes;

}

void BBoxesData::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_system_ID;
    dcdr >> m_bounding_boxes;
}

/*!
 * @brief This function sets a value in member system_ID
 * @param _system_ID New value for member system_ID
 */
void BBoxesData::system_ID(
        int16_t _system_ID)
{
    m_system_ID = _system_ID;
}

/*!
 * @brief This function returns the value of member system_ID
 * @return Value of member system_ID
 */
int16_t BBoxesData::system_ID() const
{
    return m_system_ID;
}

/*!
 * @brief This function returns a reference to member system_ID
 * @return Reference to member system_ID
 */
int16_t& BBoxesData::system_ID()
{
    return m_system_ID;
}

/*!
 * @brief This function copies the value in member bounding_boxes
 * @param _bounding_boxes New value to be copied in member bounding_boxes
 */
void BBoxesData::bounding_boxes(
        const std::vector<BBoxData>& _bounding_boxes)
{
    m_bounding_boxes = _bounding_boxes;
}

/*!
 * @brief This function moves the value in member bounding_boxes
 * @param _bounding_boxes New value to be moved in member bounding_boxes
 */
void BBoxesData::bounding_boxes(
        std::vector<BBoxData>&& _bounding_boxes)
{
    m_bounding_boxes = std::move(_bounding_boxes);
}

/*!
 * @brief This function returns a constant reference to member bounding_boxes
 * @return Constant reference to member bounding_boxes
 */
const std::vector<BBoxData>& BBoxesData::bounding_boxes() const
{
    return m_bounding_boxes;
}

/*!
 * @brief This function returns a reference to member bounding_boxes
 * @return Reference to member bounding_boxes
 */
std::vector<BBoxData>& BBoxesData::bounding_boxes()
{
    return m_bounding_boxes;
}


size_t BBoxesData::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return BBoxesData_max_key_cdr_typesize;
}

bool BBoxesData::isKeyDefined()
{
    return false;
}

void BBoxesData::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}

